import os
import pandas as pd

# Path of the Excel file generated by the previous script
excel_path = r' C:path\to\files '  # Read the Excel file

try:
    df = pd.read_excel(excel_path)
except FileNotFoundError:
    print(f"Excel file not found at: {excel_path}")
    exit(1)

# Obtain the list of unique patients and count the timepoints for each patient
patients = df['PatientID'].unique()
for patient in patients:
    num_timepoints = df[df['PatientID'] == patient]['Timepoint'].nunique()
    print(f"Patient {patient} has {num_timepoints} timepoints")

print("Timepoint count per patient completed.")
